---
- name: Include OS variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: define nginx user
  set_facts: 
    nginx_user: "{{ _nginx_user }}"
  when: nginx_user is not defined

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
