---
- name: Include OS variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family is defined

- name: define nginx user
  set_fact: 
    nginx_user: "{{ _nginx_user }}"
  when: nginx_user is not defined

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
