---
- name: Ensure APT official nginx key
  apt_key: url=http://nginx.org/keys/nginx_signing.key
  environment: "{{ nginx_env }}"
  when: ansible_os_family == 'Debian'

- name: Ensure APT official nginx repository
  apt_repository: repo="deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
  environment: "{{ nginx_env }}"
  when: ansible_os_family == 'Debian'
  register: nginx_ppa_added

- name: update cache
  apt: 
    update_cache: true

- name: Ensure nginx will reinstall if the PPA was just added.
  apt:
    name: "{{ nginx_package_name }}"
    state: absent
  when: nginx_ppa_added is changed
  notify: reinstall nginx
  register: nginx_ppa_reinstall

- name: install nginx
  apt: 
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_pkgs }}"
  environment:  "{{ nginx_env }}"
  notify: restart nginx
  when: nginx_ppa_reinstall is not changed
