---
- name: Converge
  hosts: all
  gather_facts: false
  
  vars:
      nginx_use_ppa: true
      nginx_remove_default_vhost: true
      nginx_vhosts:
        - server_name: "test.dev"
          root: "/var/www/test"
  