---
- name: Converge
  hosts: all
  gather_facts: true
  
  vars:
      nginx_remove_default_vhost: true
      nginx_vhosts:
        - server_name: "test.dev"
          root: "/var/www/test"
  
  roles: 
    - role: jantttez.nginx